# Reload config
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Prefix
set -g prefix C-o

# Pane navigation
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Terminal
set -g default-terminal "tmux-256color"
set -g mouse on

# Plugins
set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'tmux-plugins/tpm'

set -g @catppuccin_flavor 'latte'

run "~/.config/tmux/plugins/catpuccin-tmux/catppuccin.tmux"

# Make the status line more pleasant.
set -g status-left ""
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_current_text " #W*"
set -g status-right '#[fg=#{@thm_crust},bg=#{@thm_teal}] session: #S '

# Ensure that everything on the right side of the status line
# is included.
set -g status-right-length 100

# Initialize TMUX plugin manager (keep at the very bottom)
run-shell '~/.tmux/plugins/tpm/tpm'
